apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-controller
spec:
  selector:
    matchLabels:
      app: ai-controller
  template:
    metadata:
      labels:
        app: ai-controller
    spec:
      containers:
      - name: ai-controller
        image: ai-controller:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5730
